run:
  timeout: 1m

linters:
  enable-all: true
  disable:
    - exportloopref # deprecated
    - wsl
    - varnamelen
    - wrapcheck

linters-settings:
  gci:
    sections:
      - standard
      - default
      - localmodule

  depguard:
    rules:
      main:
        list-mode: lax
        deny:
          - pkg: skip

issues:
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - funlen
        - err113